name: "Training" # name for this file
desc: "Training task" # description
folder: "Task" # folder name under Assets/Resources/
image: "Training" # Instruction filename for this task, it will be shown in the instruction for participants
rule: [ "Electricity", "Gas", "Sewage", "Water" ] # construction rule
P1: [ "color", "type" ] # partial info given to P1
P2: [ "size", "length" ] # partial info given to P2
# Layout/Plan is given to the player who does not receive length, here it's P1
# Construct rule is given to another person, here it's P2
info:
  - id: 1
    segment: 1
    color: magenta # magenta/yellow/green/blue
    type: sewage # sewage/gas/electricity/water
    size: 1 # int
    length: 9.5 # float
  - id: 2
    segment: 2
    color: magenta
    type: sewage
    size: 1
    length: 4.25
  - id: 3
    segment: 3
    color: blue
    type: gas
    size: 3
    length: 4.25
  - id: 4
    segment: 4
    color: blue
    type: gas
    size: 3
    length: 9.5