name: "Training" # name for this file
desc: "Training task" # description
folder: "SheetsTables/training" # folder name under Assets/Resources/
image: "training" # Instruction filename for this task, it will be shown in the instruction for participants
rule: [ "ϕ4\"", "ϕ3\"", "ϕ1\"", "ϕ2\"" ] # construction rule
P1: [ "color", "type" ] # partial info given to P1
P2: [ "size", "length" ] # partial info given to P2
info:
  - id: 1
    segment: 1
    color: green # magenta/yellow/green/blue
    type: sewage # sewage/gas/electricity/water
    size: 1 # int
    length: 4.2 # float
  - id: 2
    segment: 2
    color: green
    type: sewage
    size: 1
    length: 9.8
  - id: 3
    segment: 3
    color: blue
    type: gas
    size: 3
    length: 3.8
  - id: 4
    segment: 4
    color: blue
    type: gas
    size: 3
    length: 9.8