# name of the scenario, correspond to the yml filename 
name: "Training"
# description of this file
desc: "Scenario training"
# normal events description in this file
normal: ""
# accidents description in this file
accident: ""
### the following 4 attributes are not in the slides, but it is referred from the original implementation
# start timestamp in raw time
start: "0:00"
# end timestamp in raw time
end: "03:00"
# start task
taskStart: 0
# end task
taskEnd: 0
# task config filename under ./Task
task: "Training.yml"
#########################################################################################################
# all incidents, including the normal events and accidents
incidents:
## The following is for debugging change order
#  - id: 1 # the order of the incident
#    time: "0:05" # start time of this incident
#    refer: [ "Irrelevant", "accidents", "1" ] # refer to which incident in the format of [vehicle, "normals/accidents", "index"]. It is defined in the Crane.yml file.
#  - id: 2
#    time: "0:10"
#    refer: [ "Irrelevant", "accidents", "2" ]
#    changeOrder: true # test change order
#  - id: 3
#    time: "0:20"
#    refer: ["Crane", "accidents", "9"] # test sagat controller
  
  
  # The following is for debugging erroneous AI
#  - id: 1
#    time: "0:05"
#    refer: [ "ErroneousAI", "accidents", "1" ]
#  - id: 2
#    time: "0:10"
#    refer: [ "ErroneousAI", "accidents", "2" ]
#    changeOrder: true
#  - id: 3
#    time: "0:15"
#    refer: ["ErroneousAI", "accidents", "3"]
#  - id: 4
#    time: "0:20"
#    refer: ["ErroneousAI", "accidents", "4"]

# The following is for debugging SAGAT
#    - id: 1
#      time: "0:05"
#      refer: [ "Crane", "accidents", "9" ] # test sagat controller

# The following is for debugging drone
#  - id: 1
#    time: "0:05"
#    refer: ["Drone", "normals", "1"]
#  - id: 2
#    time: "0:15"
#    refer: ["Drone", "normals", "2"]
#  - id: 3
#    time: "0:25"
#    refer: ["Drone", "normals", "3"]
    
# The following is for debugging crane
#  - id: 1
#    time: "0:05"
#    refer: ["Crane", "normals", "1"]
  
## The following is for debugging cranetruck
#  - id: 1
#    time: "0:05"
#    refer: ["CraneTruck", "normals", "1"]

## The following is to test independent audio sources
#  - id: 1
#    time: "0:05"
#    refer: ["CraneTruck", "normals", "1"]
#  - id: 2
#    time: "0:05"
#    refer: [ "Truck", "accidents", "1" ]

### This following is to test survey.yml
#  - id: 1
#    time: "0:10"
#    refer: ["Survey", "normals", "1"]
#  - id: 2
#    time: "1:00"
#    refer: ["Survey", "normals", "2"]
#  - id: 3
#    time: "1:10"
#    refer: ["Survey", "normals", "3"]