name: "Environment"
desc: "General questions related to environments"
questions:
  - id: 1
    label: "Q1"
    level: 1
    question: "Test question..:what kinds of potential accidents do you think were nearly happen to you and your companion? Can you describe it?"
  - id: 2
    label: "Q2"
    level: 2
    question: "Why do you think you were about to/nearly have accidents? (Please select the most dangerous accidents)"
  - id: 3
    label: "Q3"
    level: 3
    question: "What kinds of potential accidents do you think might happen to the other workers in this environment? Can you describe it?"
  - id: 4
    label: "Q4"
    level: 3
    question: "Following the previous question, why do you think they were going to have accidents?"
  - id: 5
    label: "Q5"
    level: 3
    question: "Did the AI-assistant give you the correct warning?"
  - id: 6
    label: "Q6"
    level: 3
    question: "Q6: Did the AI-assistant give you the correct warning?"