name: "Training"
desc: "Questions related to training"
questions:
    - id: 1
      label: "Q1"
      level: 1
      question: "From the safety perspective, is there anything unusual in the environment? Please describe it."
    - id: 2
      label: "Q2"
      level: 2
      question: "How do you describe the falling pipe accident?"
    - id: 3
      label: "Q3"
      level: 3
      question: "What do you expect about the crane if it comes next time? Why do you have this expectation?"
    - id: 4
      label: "Q4"
      level: 3
      question: "Where did you start to install the pipe and where did it end? From point _ to point _."
      options:
          - "A to D"
          - "A to B & D"
          - "A to B & C"
          - "D to C & A"
          - "B & D to A"
          - "C & D to B"
          - "A & B to C & D"
          - "A & C to B & D"
    - id: 5
      label: "Q5"
      level: 3
      question: "Is there anything unusual about the AI-assistant, AI drone, and robot dog?"
    - id: 6
      label: "Q6"
      level: 3
      question: "Do you have enough material (including pipe, glue, clamp) to finish the remaining task on the plan sheet? If not, how much is left?"
    - id: 7
      label: "Q7"
      level: 3
      question: "Which pipe is missing during the task?"
      options:
          - "Magenta"
          - "Blue"
          - "Green"
          - "Yellow"
    - id: 8
      label: "Q8"
      level: 3
      question: "How many times did the cargo pass overhead?"
      options:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"