//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/Animations/RobotArmInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RobotArmInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RobotArmInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RobotArmInputAction"",
    ""maps"": [
        {
            ""name"": ""RobotArm"",
            ""id"": ""2603790e-3725-4c4d-8bc5-eb0a5ddaac4b"",
            ""actions"": [
                {
                    ""name"": ""part0"",
                    ""type"": ""Value"",
                    ""id"": ""a79a0edc-f794-4639-8a24-a1076d6d953a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""part1"",
                    ""type"": ""Value"",
                    ""id"": ""8ea2505c-d106-477e-8acc-807477f16bc5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""part2"",
                    ""type"": ""Value"",
                    ""id"": ""a6c3c55e-5503-4940-8cd0-bbc6e6482c3f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""part3"",
                    ""type"": ""Value"",
                    ""id"": ""b429d7dc-2cfc-44ec-a6b5-554ef5b271c0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8a521f2e-03e1-4950-81f1-51db471604b0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part0"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f1d3f050-0268-40a4-a3ca-91a7ff13a327"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a9325796-d7c1-4d2f-8ce4-ac0ce2897bc4"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7b67ca48-0857-408d-8640-19c6c43d11f2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""77d0a39d-d46a-4eb5-999d-3af1b3cdb5d9"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7e62d39c-2dca-4f14-bb7c-9e8e30014e62"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""99316102-9265-4d85-b67f-b61751220b38"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8a0d5711-b3db-4173-9047-362cbd5f8721"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""562591fb-9fed-49e4-be0c-edd824901db5"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""3b25bd9f-6c05-4229-bc69-bd2103072f4b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8cab92a3-6242-4964-a448-32b35d034869"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""831670bd-f464-49b2-98a6-59ae2352be84"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""part3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RobotArm
        m_RobotArm = asset.FindActionMap("RobotArm", throwIfNotFound: true);
        m_RobotArm_part0 = m_RobotArm.FindAction("part0", throwIfNotFound: true);
        m_RobotArm_part1 = m_RobotArm.FindAction("part1", throwIfNotFound: true);
        m_RobotArm_part2 = m_RobotArm.FindAction("part2", throwIfNotFound: true);
        m_RobotArm_part3 = m_RobotArm.FindAction("part3", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RobotArm
    private readonly InputActionMap m_RobotArm;
    private List<IRobotArmActions> m_RobotArmActionsCallbackInterfaces = new List<IRobotArmActions>();
    private readonly InputAction m_RobotArm_part0;
    private readonly InputAction m_RobotArm_part1;
    private readonly InputAction m_RobotArm_part2;
    private readonly InputAction m_RobotArm_part3;
    public struct RobotArmActions
    {
        private @RobotArmInputAction m_Wrapper;
        public RobotArmActions(@RobotArmInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @part0 => m_Wrapper.m_RobotArm_part0;
        public InputAction @part1 => m_Wrapper.m_RobotArm_part1;
        public InputAction @part2 => m_Wrapper.m_RobotArm_part2;
        public InputAction @part3 => m_Wrapper.m_RobotArm_part3;
        public InputActionMap Get() { return m_Wrapper.m_RobotArm; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RobotArmActions set) { return set.Get(); }
        public void AddCallbacks(IRobotArmActions instance)
        {
            if (instance == null || m_Wrapper.m_RobotArmActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RobotArmActionsCallbackInterfaces.Add(instance);
            @part0.started += instance.OnPart0;
            @part0.performed += instance.OnPart0;
            @part0.canceled += instance.OnPart0;
            @part1.started += instance.OnPart1;
            @part1.performed += instance.OnPart1;
            @part1.canceled += instance.OnPart1;
            @part2.started += instance.OnPart2;
            @part2.performed += instance.OnPart2;
            @part2.canceled += instance.OnPart2;
            @part3.started += instance.OnPart3;
            @part3.performed += instance.OnPart3;
            @part3.canceled += instance.OnPart3;
        }

        private void UnregisterCallbacks(IRobotArmActions instance)
        {
            @part0.started -= instance.OnPart0;
            @part0.performed -= instance.OnPart0;
            @part0.canceled -= instance.OnPart0;
            @part1.started -= instance.OnPart1;
            @part1.performed -= instance.OnPart1;
            @part1.canceled -= instance.OnPart1;
            @part2.started -= instance.OnPart2;
            @part2.performed -= instance.OnPart2;
            @part2.canceled -= instance.OnPart2;
            @part3.started -= instance.OnPart3;
            @part3.performed -= instance.OnPart3;
            @part3.canceled -= instance.OnPart3;
        }

        public void RemoveCallbacks(IRobotArmActions instance)
        {
            if (m_Wrapper.m_RobotArmActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRobotArmActions instance)
        {
            foreach (var item in m_Wrapper.m_RobotArmActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RobotArmActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RobotArmActions @RobotArm => new RobotArmActions(this);
    public interface IRobotArmActions
    {
        void OnPart0(InputAction.CallbackContext context);
        void OnPart1(InputAction.CallbackContext context);
        void OnPart2(InputAction.CallbackContext context);
        void OnPart3(InputAction.CallbackContext context);
    }
}
